// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdmbsqaetxdsxibhwjfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkbWJzcWFldHhkc3hpYmh3amZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjEyNjgsImV4cCI6MjA2Mjc5NzI2OH0.Kdm1mr3Fu-LN5cZqrvObIN52l_0xWsNsomWRP3EWv58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);